name: butler push action
description: Pushes a local directory to itch.io using butler

inputs:
  path:
    type: string
    default: "."
  target:
    type: string
    required: true
  version:
    type: string
  version-file:
    type: string

runs:
  using: composite
  steps:
  - run: butler push "${{ inputs.path }}" ${{ inputs.target }} ${{ inputs.version != '' && format('--userversion {0}', inputs.version) }} ${{ inputs.version-file != '' && format('--userversion-file {0}', inputs.version-file) }}
    shell: bash
