name: butler push action
description: Pushes a local directory to itch.io using butler

inputs:
  path:
    default: "."
  target:
    required: true
  version:
    default: ""
  version-file:
    default: ""

runs:
  using: composite
  steps:
  - run: butler push "${{ inputs.path }}" ${{ inputs.target }} ${{ inputs.version != '' && format('--userversion {0}', inputs.version) || '' }} ${{ inputs.version-file != '' && format('--userversion-file {0}', inputs.version-file) || '' }}
    shell: bash
