name: butler push action
description: Pushes a local directory to itch.io using butler

inputs:
  path:
    type: string
    default: "."
  target:
    type: string
    required: true

runs:
  using: composite
  steps:
  - run: butler push "${{ inputs.path }}" ${{ inputs.target }}
    shell: bash
